version: '3.8'

services:
  facesentinel-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facesentinel-backend
    network_mode: "host"   # Permite conectar directamente a 127.0.0.1:5600 del Geth local
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  facesentinel-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: facesentinel-frontend
    restart: always
    ports:
      - "8088:80"          # Portal Web accesible en el puerto 8088
    depends_on:
      - facesentinel-backend
